build:
	g++ -g threadpool_test.cpp -o threadpool_test -lpthread
	g++ -g sync_task_queue_test.cpp -o sync_task_queue_test -lpthread

run1:
	./threadpool_test

run2:
	./sync_task_queue_test

clean:
	rm -rf ./threadpool_test
	rm -rf ./sync_task_queue_test